"use client";

import { useState, useEffect } from "react";
import { X, Search, User, Calendar, Clock, DollarSign, FileText } from "lucide-react";
import { appointments, patients, users, billing } from "@/services/api";

interface BookAppointmentModalProps {
    onClose: () => void;
    onSuccess: () => void;
    initialPatient?: any;
}

export default function BookAppointmentModal({ onClose, onSuccess, initialPatient }: BookAppointmentModalProps) {
    const [step, setStep] = useState(1); // 1: Select Patient, 2: Select Details, 3: Confirm & Pay
    const [searchTerm, setSearchTerm] = useState("");
    const [searchResults, setSearchResults] = useState<any[]>([]);
    const [selectedPatient, setSelectedPatient] = useState<any>(initialPatient || null);
    const [doctors, setDoctors] = useState<any[]>([]);
    const [formData, setFormData] = useState({
        doctor_id: "",
        appointment_date: new Date().toISOString().split('T')[0],
        appointment_time: "",
        reason: "",
        type: "consultation" // consultation, follow-up, emergency
    });
    const [loading, setLoading] = useState(false);
    const [searching, setSearching] = useState(false);

    // Consultation Fees
    const FEES = {
        consultation: 50,
        "follow-up": 30,
        emergency: 100
    };

    useEffect(() => {
        // Fetch doctors
        const fetchDoctors = async () => {
            try {
                const data = await users.getAll();
                // Filter for doctors (assuming role or department check, simpler for now)
                const docs = data.filter((u: any) => u.role === 'doctor' || u.role?.name === 'Doctor');
                setDoctors(docs);
            } catch (error) {
                console.error("Failed to load doctors", error);
            }
        };
        fetchDoctors();
    }, []);

    useEffect(() => {
        if (searchTerm.length > 2) {
            const delay = setTimeout(async () => {
                setSearching(true);
                try {
                    const data = await patients.getAll(); // Ideally use a search endpoint
                    const filtered = data.filter((p: any) =>
                        (p.full_name || p.user?.full_name)?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                        p.unique_id?.toLowerCase().includes(searchTerm.toLowerCase())
                    );
                    setSearchResults(filtered);
                } catch (error) {
                    console.error("Search failed", error);
                } finally {
                    setSearching(false);
                }
            }, 500);
            return () => clearTimeout(delay);
        } else {
            setSearchResults([]);
        }
    }, [searchTerm]);

    const handlePatientSelect = (patient: any) => {
        setSelectedPatient(patient);
        setStep(2);
    };

    const handleSubmit = async () => {
        setLoading(true);
        try {
            // 1. Create Appointment
            const appointmentTime = `${formData.appointment_date}T${formData.appointment_time}:00Z`;

            const appointmentData = {
                patient_id: selectedPatient.id,
                doctor_id: parseInt(formData.doctor_id),
                appointment_time: appointmentTime,
                type: 'offline', // Backend expects 'offline' or 'online'
                reason: `[${formData.type.toUpperCase()}] ${formData.reason}`, // Append type to reason
                notes: `Type: ${formData.type}`,
                status: 'pending'
            };

            // Note: API might expect different format, adjusting based on common practices
            // If the API 'create' expects combined date/time or separate, we'd adjust.
            // Using standard simplified payload for now.
            const newAppointment = await appointments.create(appointmentData);

            // 2. Invoice is automatically generated by the backend for staff bookings.
            alert("Appointment booked and Invoice generated successfully! Please proceed to Billing to settle the payment.");
            onSuccess();
            onClose();
        } catch (error) {
            console.error("Booking failed", error);
            alert("Failed to book appointment. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <div className="bg-white rounded-2xl w-full max-w-2xl overflow-hidden shadow-xl">
                <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-gray-50">
                    <h2 className="font-bold text-gray-900 text-lg">Book Appointment</h2>
                    <button onClick={onClose} className="p-2 hover:bg-gray-200 rounded-full text-gray-500">
                        <X className="w-5 h-5" />
                    </button>
                </div>

                <div className="p-6 min-h-[400px]">
                    {step === 1 && !initialPatient ? (
                        <div className="space-y-6">
                            <div className="text-center space-y-2">
                                <h3 className="text-lg font-bold text-gray-900">Find Patient</h3>
                                <p className="text-gray-500">Search by name or ID to start booking</p>
                            </div>
                            <div className="relative">
                                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                                <input
                                    type="text"
                                    placeholder="Search patient..."
                                    className="w-full pl-12 pr-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
                                    value={searchTerm}
                                    onChange={(e) => setSearchTerm(e.target.value)}
                                    autoFocus
                                />
                            </div>

                            <div className="space-y-2">
                                {searching ? (
                                    <div className="text-center py-8 text-gray-400">Searching...</div>
                                ) : searchResults.length > 0 ? (
                                    searchResults.map(patient => (
                                        <button
                                            key={patient.id}
                                            onClick={() => handlePatientSelect(patient)}
                                            className="w-full p-4 flex items-center gap-4 bg-white border border-gray-100 hover:border-blue-200 hover:bg-blue-50/50 rounded-xl transition-all group text-left"
                                        >
                                            <div className="w-10 h-10 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold">
                                                {(patient.full_name || patient.user?.full_name)?.[0]}
                                            </div>
                                            <div>
                                                <p className="font-bold text-gray-900 group-hover:text-blue-700">{patient.full_name || patient.user?.full_name}</p>
                                                <p className="text-sm text-gray-500">ID: {patient.unique_id} • {patient.gender}</p>
                                            </div>
                                        </button>
                                    ))
                                ) : searchTerm.length > 2 ? (
                                    <div className="text-center py-8 text-gray-400">No patients found</div>
                                ) : (
                                    <div className="text-center py-8 text-gray-400 text-sm">Type to search existing patients</div>
                                )}
                            </div>
                        </div>
                    ) : (
                        <div className="space-y-6">
                            {/* Selected Patient Card */}
                            <div className="flex items-center gap-4 p-4 bg-blue-50 rounded-xl border border-blue-100">
                                <div className="w-12 h-12 rounded-full bg-white text-blue-600 flex items-center justify-center font-bold text-xl shadow-sm">
                                    <User className="w-6 h-6" />
                                </div>
                                <div>
                                    <p className="text-sm text-blue-600 font-bold uppercase tracking-wider">Patient</p>
                                    <p className="text-lg font-bold text-gray-900">{selectedPatient?.full_name || selectedPatient?.user?.full_name}</p>
                                </div>
                                {!initialPatient && (
                                    <button onClick={() => setStep(1)} className="ml-auto text-sm text-blue-600 hover:underline">Change</button>
                                )}
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1.5">Doctor</label>
                                    <select
                                        className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"
                                        value={formData.doctor_id}
                                        onChange={(e) => setFormData({ ...formData, doctor_id: e.target.value })}
                                    >
                                        <option value="">Select Doctor</option>
                                        {doctors.map(doc => (
                                            <option key={doc.id} value={doc.id}>Dr. {doc.full_name}</option>
                                        ))}
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1.5">Type</label>
                                    <select
                                        className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"
                                        value={formData.type}
                                        onChange={(e) => setFormData({ ...formData, type: e.target.value })}
                                    >
                                        <option value="consultation">General Consultation</option>
                                        <option value="follow-up">Follow-up</option>
                                        <option value="emergency">Emergency</option>
                                    </select>
                                </div>
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1.5">Date</label>
                                    <div className="relative">
                                        <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                                        <input
                                            type="date"
                                            className="w-full pl-10 pr-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"
                                            value={formData.appointment_date}
                                            onChange={(e) => setFormData({ ...formData, appointment_date: e.target.value })}
                                        />
                                    </div>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1.5">Time</label>
                                    <div className="relative">
                                        <Clock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                                        <input
                                            type="time"
                                            className="w-full pl-10 pr-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"
                                            value={formData.appointment_time}
                                            onChange={(e) => setFormData({ ...formData, appointment_time: e.target.value })}
                                        />
                                    </div>
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1.5">Reason / Symptoms</label>
                                <textarea
                                    className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 resize-none h-24"
                                    placeholder="Brief description of symptoms..."
                                    value={formData.reason}
                                    onChange={(e) => setFormData({ ...formData, reason: e.target.value })}
                                ></textarea>
                            </div>

                            {/* Proposed Invoice Summary */}
                            <div className="bg-orange-50 p-4 rounded-xl border border-orange-100 flex items-center justify-between">
                                <div className="flex items-center gap-3">
                                    <div className="p-2 bg-white text-orange-600 rounded-lg shadow-sm">
                                        <DollarSign className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <p className="text-sm font-bold text-orange-800">Fee Required</p>
                                        <p className="text-xs text-orange-600">An invoice will be generated automatically</p>
                                    </div>
                                </div>
                                <p className="text-xl font-bold text-orange-900">₦{FEES[formData.type as keyof typeof FEES]}</p>
                            </div>
                        </div>
                    )}
                </div>

                <div className="p-4 border-t border-gray-100 bg-gray-50 flex justify-end gap-3">
                    <button onClick={onClose} className="px-5 py-2.5 font-medium text-gray-600 hover:bg-gray-200 rounded-xl transition-colors">
                        Cancel
                    </button>
                    {(step === 2 || initialPatient) && (
                        <button
                            onClick={handleSubmit}
                            disabled={loading || !formData.doctor_id || !formData.appointment_time}
                            className="px-6 py-2.5 bg-gray-900 text-white font-bold rounded-xl hover:bg-gray-800 transition-all shadow-lg shadow-gray-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                        >
                            {loading ? 'Booking...' : 'Confirm & Invoice'}
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
}

